// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: notificator/opensky.proto

package notificator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notificator_opensky_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_notificator_opensky_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_notificator_opensky_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Region struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Center *Location `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Radius int32     `protobuf:"varint,3,opt,name=radius,proto3" json:"radius,omitempty"`
}

func (x *Region) Reset() {
	*x = Region{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notificator_opensky_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_notificator_opensky_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_notificator_opensky_proto_rawDescGZIP(), []int{1}
}

func (x *Region) GetCenter() *Location {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *Region) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type FlightStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Callsign string    `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	ModesId  string    `protobuf:"bytes,2,opt,name=modesId,proto3" json:"modesId,omitempty"`
	Position *Location `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Altitude int32     `protobuf:"varint,4,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Heading  int32     `protobuf:"varint,5,opt,name=heading,proto3" json:"heading,omitempty"`
	Squawk   string    `protobuf:"bytes,6,opt,name=squawk,proto3" json:"squawk,omitempty"`
}

func (x *FlightStatus) Reset() {
	*x = FlightStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notificator_opensky_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightStatus) ProtoMessage() {}

func (x *FlightStatus) ProtoReflect() protoreflect.Message {
	mi := &file_notificator_opensky_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightStatus.ProtoReflect.Descriptor instead.
func (*FlightStatus) Descriptor() ([]byte, []int) {
	return file_notificator_opensky_proto_rawDescGZIP(), []int{2}
}

func (x *FlightStatus) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *FlightStatus) GetModesId() string {
	if x != nil {
		return x.ModesId
	}
	return ""
}

func (x *FlightStatus) GetPosition() *Location {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *FlightStatus) GetAltitude() int32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *FlightStatus) GetHeading() int32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *FlightStatus) GetSquawk() string {
	if x != nil {
		return x.Squawk
	}
	return ""
}

var File_notificator_opensky_proto protoreflect.FileDescriptor

var file_notificator_opensky_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x73, 0x6b, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x44, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x4f,
	0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22,
	0xc5, 0x01, 0x0a, 0x0c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x6f, 0x64, 0x65, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x6f, 0x64, 0x65, 0x73, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x6c, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x71, 0x75, 0x61, 0x77, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x71, 0x75, 0x61, 0x77, 0x6b, 0x32, 0x55, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x46, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x1a,
	0x19, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x30, 0x01, 0x42, 0x30,
	0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x72,
	0x69, 0x73, 0x64, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x6b, 0x79, 0x2d, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notificator_opensky_proto_rawDescOnce sync.Once
	file_notificator_opensky_proto_rawDescData = file_notificator_opensky_proto_rawDesc
)

func file_notificator_opensky_proto_rawDescGZIP() []byte {
	file_notificator_opensky_proto_rawDescOnce.Do(func() {
		file_notificator_opensky_proto_rawDescData = protoimpl.X.CompressGZIP(file_notificator_opensky_proto_rawDescData)
	})
	return file_notificator_opensky_proto_rawDescData
}

var file_notificator_opensky_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notificator_opensky_proto_goTypes = []interface{}{
	(*Location)(nil),     // 0: notificator.Location
	(*Region)(nil),       // 1: notificator.Region
	(*FlightStatus)(nil), // 2: notificator.FlightStatus
}
var file_notificator_opensky_proto_depIdxs = []int32{
	0, // 0: notificator.Region.center:type_name -> notificator.Location
	0, // 1: notificator.FlightStatus.position:type_name -> notificator.Location
	1, // 2: notificator.Notificator.GetRegionUpdates:input_type -> notificator.Region
	2, // 3: notificator.Notificator.GetRegionUpdates:output_type -> notificator.FlightStatus
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notificator_opensky_proto_init() }
func file_notificator_opensky_proto_init() {
	if File_notificator_opensky_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notificator_opensky_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notificator_opensky_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Region); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notificator_opensky_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notificator_opensky_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificator_opensky_proto_goTypes,
		DependencyIndexes: file_notificator_opensky_proto_depIdxs,
		MessageInfos:      file_notificator_opensky_proto_msgTypes,
	}.Build()
	File_notificator_opensky_proto = out.File
	file_notificator_opensky_proto_rawDesc = nil
	file_notificator_opensky_proto_goTypes = nil
	file_notificator_opensky_proto_depIdxs = nil
}
